services:
  backend:
    build:
      context: ./backend  # Indica que el Dockerfile se encuentra en la carpeta 'backend'
    ports:
      - "8000:8000"  # Mapea el puerto 8000 del contenedor al puerto 8000 en el host
    volumes:
      - ./backend/app:/app/app  # Sincroniza la carpeta 'app' del host con la del contenedor
  
  frontend:
    build:
      context: ./frontend  # Indica que el Dockerfile se encuentra en la carpeta 'frontend'
    ports:
      - "3000:3000"  # Mapea el puerto 3000 del contenedor al puerto 3000 en el host
    volumes:
      - ./frontend/src:/app/src  # Sincroniza la carpeta 'src' del host con la del contenedor
      - ./frontend/public:/app/public  # Sincroniza la carpeta 'public' del host con la del contenedor
    environment:
      - CHOKIDAR_USEPOLLING=true  # Habilita el polling para la detección de cambios en archivos

